SELECT SERVERID
	,ISDEFAULTREPORTMODELSERVER
	,SERVERURL
	,ISDEFAULTREPORTLIBRARYSERVER
	,AXAPTAREPORTFOLDER
	,[DESCRIPTION]
	,DATASOURCENAME
	,REPORTMANAGERURL
	,SERVERINSTANCE
	,AOSID
	,CONFIGURATIONID
	,ISSHAREPOINTINTEGRATED
	,RECVERSION
	,RECID
FROM SRSSERVERS